optimizer: CD
stopcondition {
  all_processed: false
  steps: 2000000
}
train: true
batchsize: 8
data_proto: "./piglets_data.pbtxt"
eval_after: 500
checkpoint_after: 58500
checkpoint_directory: "./output_181220"
randomize: false
show_after: 2500