%-----------------------------------------------------------------------
% Job saved on 12-Feb-2019 16:54:09 by cfg_util (rev $Rev: 7345 $)
% spm SPM - SPM12 (7487)
% cfg_basicio BasicIO - Unknown
%-----------------------------------------------------------------------


matlabbatch{1}.spm.tools.oldnorm.write.subj.matname = {'/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/piglet_analysis/masked_normalize_sliced_unwarp_fmri_sn.mat'};
%%
matlabbatch{1}.spm.tools.oldnorm.write.subj.resample = {
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,1'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,2'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,3'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,4'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,5'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,6'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,7'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,8'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,9'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,10'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,11'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,12'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,13'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,14'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,15'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,16'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,17'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,18'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,19'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,20'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,21'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,22'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,23'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,24'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,25'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,26'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,27'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,28'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,29'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,30'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,31'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,32'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,33'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,34'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,35'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,36'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,37'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,38'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,39'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,40'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,41'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,42'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,43'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,44'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,45'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,46'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,47'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,48'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,49'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,50'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,51'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,52'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,53'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,54'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,55'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,56'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,57'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,58'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,59'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,60'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,61'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,62'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,63'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,64'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,65'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,66'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,67'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,68'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,69'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,70'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,71'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,72'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,73'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,74'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,75'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,76'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,77'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,78'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,79'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,80'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,81'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,82'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,83'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,84'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,85'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,86'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,87'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,88'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,89'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,90'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,91'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,92'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,93'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,94'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,95'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,96'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,97'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,98'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,99'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,100'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,101'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,102'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,103'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,104'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,105'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,106'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,107'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,108'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,109'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,110'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,111'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,112'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,113'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,114'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,115'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,116'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,117'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,118'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,119'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,120'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,121'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,122'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,123'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,124'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,125'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,126'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,127'
                                                        '/home/local/AIUGA/clm121/Documents/deepnet/deepnet/rbm_piglets/Smoothed125_ThresZ1_rbm_piglets_weights_reconstructed_Corrected_last.nii,128'
                                                        };
%%
matlabbatch{1}.spm.tools.oldnorm.write.roptions.preserve = 0;
matlabbatch{1}.spm.tools.oldnorm.write.roptions.bb = [-63.5 -57.75 -24.5
                                                      64 70 31];
matlabbatch{1}.spm.tools.oldnorm.write.roptions.vox = [-0.5 0.5 0.5];
matlabbatch{1}.spm.tools.oldnorm.write.roptions.interp = 7;
matlabbatch{1}.spm.tools.oldnorm.write.roptions.wrap = [0 0 0];
matlabbatch{1}.spm.tools.oldnorm.write.roptions.prefix = 'norm/normalize_';
